services:
  postgres:
    image: postgres:15-alpine
    container_name: feast_postgres
    restart: unless-stopped
    env_file: [.env]
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-feast_demo}
      POSTGRES_USER: ${POSTGRES_USER:-feast}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-feast}
    ports:
      - "${POSTGRES_PORT:-5050}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: feast_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
